// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swcdcqvgadckxnsznxtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Y2RjcXZnYWRja3huc3pueHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTM1MDQsImV4cCI6MjA2NTQ4OTUwNH0.urqplHaB40hKYneB7yXc9QPQSPBZSRy-BBX09ViAdNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);